telegram:
  creator:
    id: ENC(XTQfepj29h3jk+kwHcDfIt/lzvLcvaMpWxLme6VEodP8Rpz26t/g98sXvUC/gtah)
  bots:
    bilubot:
      token: ENC(YP9Uj1Qhbnw3KDxIFUo2t9P66g7r1G5tAVa9JVR08BV0dr4ESnEOpCGco+P9fXPKJIZPlyIaqk5AN4aIHOwU2LWkYltEhwa8K1qL5/lY0Wg=)
      username: ENC(j5VE3XUUOMmQcm2hkPBdEN/jtfHHvoRT28AMxR45JxenR+JI+gyeoBqQaQKiKiI2)
      upload-channel-id: ENC(CZejpeFij0pRY6Wo7qXrH+f44AjGSRUUtRcXOQqRzimLDMtMQs53SRTrslllGOeP)
