server:
  port: 8090
telegram:
  creator:
    id: ENC(XTQfepj29h3jk+kwHcDfIt/lzvLcvaMpWxLme6VEodP8Rpz26t/g98sXvUC/gtah)
  bots:
    bilubot:
      token: ENC(6YGyqJmbLbPLW97UQjK5J85BTjMIpA+oJvluiTsKjZOUHImY5yU3vSwfYoSR2bRXhCmxQWt0lenHB7XjBGRQ9I3SQJSjqEn+1qF1dcYLf9I=)
      username: ENC(g4FTdu3Q7fVT1d+z4dhVHs3T2NcsdFTC+orIqTSxsoj8IVb6gFOJkI3ZXrI5MtiB)
      upload-channel-id: ENC(CZejpeFij0pRY6Wo7qXrH+f44AjGSRUUtRcXOQqRzimLDMtMQs53SRTrslllGOeP)
