telegram:
  creator:
    id: ENC(XTQfepj29h3jk+kwHcDfIt/lzvLcvaMpWxLme6VEodP8Rpz26t/g98sXvUC/gtah)
  bots:
    bilubot:
      token: ENC(lj4Z8Mnv218sz8/d73/2nqCf7/y5n+prVg5951ISY6O4DU5TPd45L6h5zuJippVsp97uLWgT5VbQ1REbbnqaOj5MGDKUlscriwJy8SZ1tI0=)
      username: ENC(oSlTZJFM6KTmANNvXvpAk+DRtogMaRJZjF5NghvrGX2EyxIg223aCXhBlhrJaoDe)
      upload-channel-id: ENC(CZejpeFij0pRY6Wo7qXrH+f44AjGSRUUtRcXOQqRzimLDMtMQs53SRTrslllGOeP)
