name: Build and Test Pull Request

on:
  pull_request:
    branches: [ main ]

jobs:
  build-and-test-pull-request:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version-file: '.tool-versions'
          distribution: 'oracle'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean build
      - name: Test with Gradle
        run: ./gradlew test
