name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
  workflow_dispatch:
    inputs:
      create_release:
        description: 'Create a new release'
        required: true
        default: 'true'

jobs:
  release:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'workflow_dispatch' }}

    steps:
      - uses: actions/checkout@v3
      - name: Download JAR artifact
        uses: actions/download-artifact@v3
        with:
          name: jar-artifact
      - name: Release with semantic-release
        if: ${{ github.event_name != 'workflow_dispatch' || github.event.inputs.create_release == 'true' }}
        uses: cycjimmy/semantic-release-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Deploy to server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            # Create the directory if it doesn't exist
            mkdir -p /home/ubuntu/bots/bilubot-java
            
            # Stop the running application (if any)
            if pgrep -f "bilubot-java.jar" > /dev/null
            then
              pkill -f "bilubot-java.jar"
            fi
            
            # Remove the old JAR file
            rm -f /home/ubuntu/bots/bilubot-java/bilubot-java.jar
            
            # Copy the new JAR file to the server
            scp -r build/libs/*.jar ubuntu@${{ secrets.SERVER_HOST }}:/home/ubuntu/bots/bilubot-java/bilubot-java.jar
            
            # Start the new version of the application
            nohup java -jar /home/ubuntu/bots/bilubot-java/bilubot-java.jar > /home/ubuntu/bots/bilubot-java/bilubot-java.log 2>&1 &
#      - name: Health test
#        run: |
#          response=$(curl -s -o /dev/null -w "%{http_code}" http://${{ secrets.SERVER_HOST }}:${{ secrets.SERVER_PORT }}/actuator/health)
#          if [[ $response -eq 200 ]]; then
#            echo "Health check passed"
#          else
#            echo "Health check failed"
#            exit 1
#          fi